---
- name: Apache server installed
  hosts: web

  tasks:

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: false
      state: stopped
      
  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: disabled
      immediate: yes
      
  - name: latest Apache version installed
    yum:
      name: httpd
      state: absent
